apiVersion: v1
kind: Secret
metadata:
  name: service-account-credentials
type: Opaque
stringData:
  RHOAS_SERVICE_ACCOUNT_CLIENT_ID: {{ .Values.client.id }}
  RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET: {{ .Values.client.secret }}
  RHOAS_SERVICE_ACCOUNT_OAUTH_TOKEN_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token